name: survey_flutter
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http:
  provider:
  equatable:
  get: 4.3.8
  flutter_secure_storage:
  localstorage:
  carousel_slider:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^2.0.0
  test: 
  mocktail: 
  faker: 

flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/

flutter_icons:
  ios: true
  android: true
  image_path_android: lib/ui/assets/icon/android1.png
  image_path_ios: lib/ui/assets/icon/ios1.png
  adaptive_icon_background: lib/ui/assets/icon/background.png
  adaptive_icon_foreground: lib/ui/assets/icon/foreground.png